name: rosemary
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.0
  http: ^0.13.3
  url_launcher: ^6.0.9
  flutter_launcher_icons: ^0.9.1
  shared_preferences: ^2.0.6
  image_picker: ^0.8.3+1
  dio: ^4.0.0
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  timezone: ^0.8.0
  connectivity: ^3.0.6
  carousel_slider: ^4.0.0
  filter_list: ^1.0.0
  sizer: ^2.0.13
  map_launcher: ^2.1.1
  geocoding: ^2.0.1
  google_maps_flutter: ^2.0.8
  badges: ^2.0.1
  async: ^2.6.1
  flutter_blurhash: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/rosemary.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/header.jpg
    - assets/visa.png
    - assets/kaspi.png
    - assets/rosemary_dark.jpg
    - assets/goods_images/product1.jpg
    - assets/goods_images/product2.jpg
    - assets/goods_images/product3.jpg
    - assets/goods_images/product4.jpg
    - assets/goods_images/product5.jpg
    - assets/goods_images/product6.jpg
    - assets/goods_images/product7.jpg
    - assets/goods_images/product8.jpg

  fonts:
    - family: Merriweather-Regular
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
    - family: Merriweather-Bold
      fonts:
        - asset: fonts/Merriweather-Bold.ttf
    - family: SolomonSans-SemiBold
      fonts:
        - asset: fonts/Solomon Sans SemiBold.otf
