import 'package:sizer/sizer.dart';

//GENERAL
double APP_SCREEN_CONTENT_PADDING_H_WIDTH = 4.w;
double APP_SCREEN_CONTENT_PADDING_V_WIDTH = 1.5.h;

//APPBAR
double APP_BAR_ICONS = 6.6.w;
double APP_BAR_ICONS_PADDING_LEFT = 2.5.w;
double APP_BAR_ICONS_PADDING_RIGHT = 2.5.w;

//NAVIGATION DRAWER
double DRAWER_ITEMS_VERTICAL_MARGIN = 0.2.h;

double SHOPPING_CART_COUNTER_HORIZONTAL = 1.5.w;
double SHOPPING_CART_COUNTER_VERTICAL = 0.01.w;
